# Generated by Django 2.1.4 on 2020-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='ДР'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пол'),
        ),
    ]
