# Generated by Django 2.1.4 on 2020-06-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancefreeze',
            name='withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.Withdraw'),
        ),
        migrations.AlterField(
            model_name='balancefreeze',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.Bet'),
        ),
    ]
