# Generated by Django 2.1.4 on 2020-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_auto_20200624_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменеия'),
        ),
    ]
