# Generated by Django 2.2.7 on 2020-06-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_withdraw_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yandex_wallet',
        ),
        migrations.AddField(
            model_name='bet',
            name='is_no_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balancefreeze',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_result_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Результат сумма'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Коэффициент '),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кошелек ЯД')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер карты')),
                ('card_vcv', models.CharField(blank=True, max_length=50, null=True, verbose_name='CVC')),
                ('card_valid', models.CharField(blank=True, max_length=50, null=True, verbose_name='VALID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
