# Generated by Django 2.2.7 on 2020-06-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20200625_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.UserCard'),
        ),
    ]
