# Generated by Django 2.2.7 on 2020-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_withdraw_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMail')),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
        ),
    ]
