# Generated by Django 2.2.7 on 2020-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20200623_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='coefficient',
            field=models.IntegerField(default=0, verbose_name='Коэффициент '),
        ),
    ]
