# Generated by Django 2.2.7 on 2020-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_bet_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Коэффициент '),
        ),
    ]
