# Generated by Django 2.2.7 on 2020-06-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_messageform_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пол'),
        ),
    ]
