# Generated by Django 2.2.7 on 2020-06-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0010_bet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancefreeze',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.Bet'),
        ),
    ]
