# Generated by Django 2.1.4 on 2020-07-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0010_auto_20200629_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
