# Generated by Django 2.1.4 on 2020-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0011_auto_20200706_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='qiwi_wallet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кошелек Qiwi'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='webmoney_wallet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кошелек Webmonye'),
        ),
    ]
