# Generated by Django 2.2.7 on 2020-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0011_balancefreeze_bet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Лог действий', 'verbose_name_plural': 'Логи действий'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_result_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Результат сумма'),
        ),
    ]
