# Generated by Django 2.2.7 on 2020-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='user',
            name='yandex_wallet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кошелек ЯД'),
        ),
    ]
