# Generated by Django 2.1.4 on 2020-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('is_first', models.BooleanField(default=False, verbose_name='Отображается на главной?')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='От')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('avatar', models.ImageField(blank=True, upload_to='feedback/', verbose_name='Фото от')),
            ],
        ),
    ]
