# Generated by Django 2.2.7 on 2020-06-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Отображается на главной?'),
        ),
    ]
