# Generated by Django 2.2.7 on 2020-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faq_is_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='От')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('avatar', models.ImageField(blank=True, upload_to='feedback/', verbose_name='Фото от')),
            ],
        ),
    ]
