# Generated by Django 2.1.4 on 2020-08-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_post',
            field=models.ImageField(null=True, upload_to='article/', verbose_name='Изображение превью 200x200)'),
        ),
    ]
