# Generated by Django 3.1 on 2020-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='TITLE'),
        ),
    ]
